from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field, field_validator

Severity = Literal["Low", "Medium", "High", "Critical"]


class AnalyzeRequest(BaseModel):
    query: str = Field(..., min_length=1, max_length=2000)

    @field_validator("query")
    @classmethod
    def not_blank(cls, value: str) -> str:
        stripped = value.strip()
        if not stripped:
            raise ValueError("query must not be blank")
        return stripped


class SourceRef(BaseModel):
    """A retrieved chunk that supported the analysis, with its retrieval score."""

    source: str
    threat_type: str
    chunk_index: int
    score: float


class MitreTechnique(BaseModel):
    """A MITRE ATT&CK technique extracted directly from the source documents.

    id/name are parsed deterministically out of the retrieved threat-intel files
    (see services/threat_analysis.py) rather than generated by the LLM, so a
    technique can only appear here if it is actually present in the knowledge base.
    """

    id: str
    name: str


class LLMAnalysisFragment(BaseModel):
    """The narrative portion of the analysis, generated by the LLM from retrieved
    context only. threat / mitre_attack / sources are deliberately NOT part of this
    model -- they are derived deterministically from retrieval metadata instead, so
    the LLM cannot fabricate them.
    """

    severity: Severity
    summary: str
    attack_vectors: list[str] = Field(default_factory=list)
    indicators: list[str] = Field(default_factory=list)
    mitigations: list[str] = Field(default_factory=list)
    insufficient_context: bool = Field(
        default=False,
        description=(
            "True if the retrieved context does not actually support answering the "
            "query (including when the query is unrelated to cybersecurity)."
        ),
    )


class ThreatCategory(BaseModel):
    """A threat type available in the local knowledge base, discovered from
    data/threat_intel/*.txt -- not a curated or fabricated list."""

    threat_type: str
    source: str
    description: str


class VectorStoreStatus(BaseModel):
    available: bool
    chunk_count: int
    collection: str


class LLMStatus(BaseModel):
    model: str
    reachable: bool
    model_pulled: bool


class HealthResponse(BaseModel):
    status: str
    vector_store: VectorStoreStatus
    llm: LLMStatus


class ReadinessChecks(BaseModel):
    """Per-dependency detail behind GET /ready's overall `ready` flag."""

    vector_store: bool
    llm: bool
    classifier: bool


class ReadinessResponse(BaseModel):
    """GET /ready: whether required runtime dependencies are available for serving
    protected functionality (RAG + classifier + LLM). Distinct from GET /health,
    which only reports process/application health and never reflects the classifier
    or fails the request -- see README "Health vs Readiness"."""

    ready: bool
    checks: ReadinessChecks


class LoginRequest(BaseModel):
    username: str = Field(..., min_length=1)
    password: str = Field(..., min_length=1)


class AuthStatusResponse(BaseModel):
    """Response for /auth/login, /auth/logout, and /auth/me. Never carries the
    session token itself -- that only ever travels via the HttpOnly cookie."""

    authenticated: bool
    username: str | None = None
    # "demo" for the env-credential bootstrap login (backend/services/auth.py), the
    # user's database id (as a string) for a registered account, or None when
    # unauthenticated. Never a value that could be used as a credential on its own.
    user_id: str | None = None


class RegisterRequest(BaseModel):
    """POST /auth/register body. Validation beyond "non-empty" (username shape,
    password strength, duplicate detection) happens in backend/services/users.py,
    not here -- those rules are also needed for programmatic callers of that module,
    so keeping this schema thin avoids duplicating them."""

    username: str = Field(..., min_length=1, max_length=128)
    password: str = Field(..., min_length=1, max_length=256)


class UserPublicResponse(BaseModel):
    """POST /auth/register's response. Deliberately excludes password and
    password_hash -- see backend/services/users.py::UserPublic, which this mirrors."""

    id: str
    username: str
    created_at: datetime


class ThreatAnalysis(BaseModel):
    """The /analyze response."""

    query: str
    status: Literal["analyzed", "no_relevant_intelligence"]
    threat: str | None = None
    severity: Severity | None = None
    summary: str
    attack_vectors: list[str] = Field(default_factory=list)
    mitre_attack: list[MitreTechnique] = Field(default_factory=list)
    indicators: list[str] = Field(default_factory=list)
    mitigations: list[str] = Field(default_factory=list)
    sources: list[SourceRef] = Field(default_factory=list)
